### PR TITLE
Added hover effect and removed blur effect

### PR DESCRIPTION
**Pull request by deek121477**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # 79

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 

Hover effect

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
hey @deek121477 what u have done ...u have to make a changes in style.css which is  in assets<css<style.css<
but u  have created a whole style.css 
kindly update ASAP

**Comment by Ayan-thecodeking** [comment]
> hey @deek121477 what u have done ...u have to make a changes in style.css which is in assets<css<style.css<
> but u have created a whole style.css
> kindly update ASAP

**Comment by deek121477** [comment]
> hey @deek121477 what u have done ...u have to make a changes in style.css which is in assets<css<style.css<
> but u have created a whole style.css
> kindly update ASAP
Ok

**Comment by deek121477** [comment]
> hey @deek121477 what u have done ...u have to make changes in style.css which is in assets<css<style.css<
> but u have created a whole style.css
> kindly update ASAP

I have made changes in that only

**Pull request merged**
