### PR TITLE
added html&css files

### PR DESCRIPTION
**Pull request by aishwaryas15**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
hey @aishwaryas15 please attach the ss here ..

**Comment by aishwaryas15** [comment]
Screenshot (89)

**Comment by aishwaryas15** [comment]
Screenshot (91)

**Review by Ayan-thecodeking — CHANGES_REQUESTED** [review]
cool @aishwaryas15  but can u plz change the bg image .... some thing like more 
attractive

**Comment by aishwaryas15** [comment]
Ya, sure I'll change then.. this is from Unsplash so every day it will be changing after refresh every day.

**Comment by Ayan-thecodeking** [comment]
> Ya, sure I'll change then.. this is from Unsplash so every day it will be changing after refresh every day.

ok @aishwaryas15 ...but the bg is repeated kindly make the changes

**Review by Ayan-thecodeking — CHANGES_REQUESTED** [review]
Bg is repeated kindly upadte

**Comment by aishwaryas15** [comment]
bg1
bg2
Is it fine? So i can further merge it

**Comment by aishwaryas15** [comment]
BG1 (2)
BG2 (2)
Is it fine? So I can further merge it.

**Comment by Ayan-thecodeking** [comment]
ok now its cool @aishwaryas15 :)

**Pull request merged**
