### PR TITLE
Added PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by Anupam-Panwar**
* Added PULL_REQUEST_TEMPLATE.md file in .github folder
* Desired content has been copied to this file

Fixes #35

### CODE REVIEW

**Review by rohan-kulkarni-25 — APPROVED** [review]
Great !

**Comment by Anupam-Panwar** [comment]
Hello @rohan-kulkarni-25 
I am having a simple question 
Will this PR count towards DCP 21 Program ?

**Comment by Ayan-thecodeking** [comment]
> Hello @rohan-kulkarni-25
> I am having a simple question
> Will this PR count towards DCP 21 Program ?

No @Anupam-Panwar ...only after 10th July

**Comment by Anupam-Panwar** [comment]
> > Hello @rohan-kulkarni-25
> > I am having a simple question
> > Will this PR count towards DCP 21 Program ?
> 
> No @Anupam-Panwar ...only after 10th July

Alright @Ayan-thecodeking

**Pull request merged**
