### PR TITLE
Added Favicon

### LINKED ISSUE #51: Adding Favicon as Coder's Evoke Logo
**Is your feature request related to a problem? Please describe.**

Favicon can be added in website tab it can be coders evoke logo till the design gets  ready

### PR DESCRIPTION
**Pull request by RakeshCharpe**
# Description
I added the favicon for the website

Fixes #51  

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- [x ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
Screenshot (71)

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
WhatsApp Image 2021-07-18 at 10 59 38 AM
@RakeshCharpe u have to add like this ...can u do that

**Comment by RakeshCharpe** [comment]
Can you share this icon or image with me then I can add it into favicon.

**Comment by Ayan-thecodeking** [comment]
> WhatsApp Image 2021-07-18 at 10 59 38 AM
> @RakeshCharpe u have to add like this ...can u do that

ya sure @RakeshCharpe r u in our discord ?

**Comment by RakeshCharpe** [comment]
Yes

**Comment by Ayan-thecodeking** [comment]
hey @RakeshCharpe make a PR again after adding logo

**Pull request closed without merging**
