### PR TITLE
Removed footer section and other minor changes

### PR DESCRIPTION
**Pull request by Aditya664**
# Description

Removed duplicate footer section from evet  page and other minor changes has be done.

Fixes # (208) 

## Type of change
minor and major 

# Explain the Testing instructions

**Test Configuration**:
* Operating system: widnows
* Version:10
* Text-editors used:vs code
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
https://noob-coder-07.github.io/CodersEvoke_website/contact.html

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
we are redesigning the full website ...you can check it out in issues ?

**Comment by Aditya664** [comment]
Sure

**Comment by Aditya664** [comment]
Hey @Ayan-thecodeking can you check and mearge this pull request

**Comment by Ayan-thecodeking** [comment]
> Hey @Ayan-thecodeking can you check and mearge this pull request

please check out the issues and readme ....please dont make any contribution in existing design ..
as we are working on new designs 
@Aditya664

**Pull request closed without merging**
