### PR TITLE
Given footers to events & contact 

### PR DESCRIPTION
**Pull request by Ritwik880**
This will solve #151 

Earlier:
Screenshot (331)

After giving footer :
Screenshot (335)

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
@Ritwik880 just add social handles on footer

**Comment by Ritwik880** [comment]
@Ayan-thecodeking  Fixed it, please have a look.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking Fixed it, please have a look.

thanx for contributions @Ritwik880 ....is it responsive ??? let me know

**Comment by Ritwik880** [comment]
@Ayan-thecodeking yes it is, you can see below:
Screenshot (336)

**Pull request merged**
