### PR TITLE
added footer in home and contact page.

### LINKED ISSUE #93: Add footer section and in contact us page

### PR DESCRIPTION
**Pull request by shindesuyog**
# Description

Added footer 

1st. Fixes #93 
2nd. fixed goto top button bug

### fixed goto to top button

Web capture_19-7-2021_2140_127 0 0 1

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
Hey @shindesuyog remove the curve radius frm footer and decrease the height of footer and then add a clip or ss

**Review by Ayan-thecodeking — CHANGES_REQUESTED** [review]
Hey @shindesuyog remove the curve radius frm footer and decrease the height of footer and then add a clip or ss

**Comment by shindesuyog** [comment]
Made changes

**Review by Ayan-thecodeking — CHANGES_REQUESTED** [review]
please resolve the merge conflicts @shindesuyog

**Comment by shindesuyog** [comment]
@Ayan-thecodeking created new PR #140 as there were lot of conflict.
please check #140 and merge it.

**Pull request closed without merging**
