### PR TITLE
adjusted the border Radius

### PR DESCRIPTION
**Pull request by ishan-pf**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #145 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system: windows 
* Version: 10
* Text-editors used: Vscode
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by ishan-pf** [comment]
Screenshot 2021-07-26 142730

**Comment by ishan-pf** [comment]
Screenshot 2021-07-26 145532

**Comment by neelshah2409** [comment]
@ishan-pf Please mention issue number and description in the above description of PR.

**Comment by ishan-pf** [comment]
okay i did it

**Comment by Ayan-thecodeking** [comment]
thanks @ishan-pf for ur contributions

**Pull request merged**
