### PR TITLE
Fixed Horizontal Scrollbar

### PR DESCRIPTION
**Pull request by mayank-wadhwa-git**
# Description

Fixed scrollbar

Fixes # (96)

### CODE REVIEW

**Comment by neelshah2409** [comment]
@mayank-wadhwa-git Please add the screenshot here in the description.

**Comment by mayank-wadhwa-git** [comment]
Added Screenshots

Before Fixing
not fixed

After fixing
fixed

**Comment by Ayan-thecodeking** [comment]
hey @mayank-wadhwa-git what u have changed ??

**Comment by mayank-wadhwa-git** [comment]
> hey @mayank-wadhwa-git what u have changed ??

I have fixed the horizontal scroll bar. When opening the site, there was a scroll bar at bottom also to slide horizontally which i have removed

**Comment by mayank-wadhwa-git** [comment]
in the above picture ,you can see the white space but in another ss it is not there

**Comment by Ayan-thecodeking** [comment]
> in the above picture ,you can see the white space but in another ss it is not there

okk

**Pull request merged**
