### PR TITLE
Added Responsiveness

### LINKED ISSUE #94: Add over all responsiveness in the website

### PR DESCRIPTION
**Pull request by souravseal99**
# Description

## Type of change
- [x] Added Responsiveness
- [x] fixed the position of Scroll to Top btn for easy access in smaller screens
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Attachments

https://user-images.githubusercontent.com/69809086/126741990-91ccc37d-42fb-461a-af7c-8cb6122143d6.mp4

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
@souravseal99  add any ss or video clips ...to show responsiveness

**Comment by souravseal99** [comment]
> @souravseal99  add any ss or video clips ...to show responsiveness

Sure @Ayan-thecodeking, updating it shortly with a video file.

**Comment by Ayan-thecodeking** [comment]
> > @souravseal99  add any ss or video clips ...to show responsiveness
> 
> Sure @Ayan-thecodeking, updating it shortly with a video file.

good work @souravseal99 ....hope u will contribute more 
thank you:)

**Comment by Ayan-thecodeking** [comment]
hey @souravseal99 have u added responsiveness in other pages ???

**Comment by souravseal99** [comment]
> hey @souravseal99 have u added responsiveness in other pages ???

Really sorry, I thought there was only the home page. 
Please give a moment, I will push the rest of the changes very soon.

**Comment by Ayan-thecodeking** [comment]
> > hey @souravseal99 have u added responsiveness in other pages ???
> 
> Really sorry, I thought there was only the home page.
> Please give a moment, I will push the rest of the changes very soon.

yup update it

**Comment by souravseal99** [comment]
> > > hey @souravseal99 have u added responsiveness in other pages ???
> > 
> > 
> > Really sorry, I thought there was only the home page.
> > Please give a moment, I will push the rest of the changes very soon.
> 
> yup update it




# Added Responsiveness to contact us page

- The events page was already responsive, so I left that as it was.
- The index.html file was causing a merge conflict, I accepted the incoming changes and resolved it.

image

**Review by Ayan-thecodeking — CHANGES_REQUESTED** [review]
hey @souravseal99 ..please resolve the merge conflicts and make a PR ....

**Comment by Ayan-thecodeking** [comment]
> hey @souravseal99 ..please resolve the merge conflicts and make a PR ....

@souravseal99 plz update that

**Comment by souravseal99** [comment]
> > hey @souravseal99 ..please resolve the merge conflicts and make a PR ....
> 
> @souravseal99 plz update that

yes @Ayan-thecodeking , updated it. Please let me know, if it seems good to you.

**Comment by souravseal99** [comment]
> hey @souravseal99 ..please resolve the merge conflicts and make a PR ....

should I make a new PR ?

**Comment by Ayan-thecodeking** [comment]
> > hey @souravseal99 ..please resolve the merge conflicts and make a PR ....
> 
> should I make a new PR ?

Ya sure @souravseal99

**Comment by souravseal99** [comment]
> > hey @souravseal99 ..please resolve the merge conflicts and make a PR....
> 
> @souravseal99 plz update that

hey @Ayan-thecodeking, While resolving the merge conflicts, I found out that the main branch has a bug in the hamburger menu.
As I had to sync my code with the main branch, my working branch i.e. responsiveness, now also synced that bug from there.
For now I am only committing the changes required for the responsiveness and later on we can create a different issue regarding that.

**Comment by souravseal99** [comment]
> > > hey @souravseal99 ..please resolve the merge conflicts and make a PR ....
> > 
> > 
> > should I make a new PR ?
> 
> Ya sure @souravseal99

Ok sure @Ayan-thecodeking , making a new PR shortly.

**Comment by souravseal99** [comment]
> > > > hey @souravseal99 ..please resolve the merge conflicts and make a PR ....
> > > 
> > > 
> > > should I make a new PR ?
> > 
> > 
> > Ya sure @souravseal99
> 
> Ok sure @Ayan-thecodeking , making a new PR shortly.

just made the PR @Ayan-thecodeking, please let me know if you want me to make any further changes.

**Pull request merged**
