### PR TITLE
Added evoke logo in all pages

### LINKED ISSUE #180: Set coders evoke logo in same ratio/size for every page

### PR DESCRIPTION
**Pull request by Ritwik880**
This will fix #180 

Below are some changed pages:

Screenshot (362)

Screenshot (361)

Screenshot (360)

Screenshot (359)

Screenshot (358)

Screenshot (357)

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
@Ritwik880 just increase the size a bit

**Comment by Ritwik880** [comment]
Hey @Ayan-thecodeking how is it now?

Screenshot (364)

**Comment by Ayan-thecodeking** [comment]
Now it's ok @Ritwik880 hv u updated in every page ??

**Comment by Ritwik880** [comment]
@Ayan-thecodeking  

> Now it's ok @Ritwik880 hv u updated in every page ??

@Ayan-thecodeking Yes

Screenshot (365)
Screenshot (366)
Screenshot (367)
Screenshot (368)
Screenshot (369)

**Comment by Ayan-thecodeking** [comment]
thnx @Ritwik880

**Pull request merged**
