### PR TITLE
created transition in navbar anchor tags

### LINKED ISSUE #102: Add transition in navbar anchor tags
Box one in hover effect

### PR DESCRIPTION
**Pull request by dilroseR**
# Description
created transition in navbar anchor tags

Fixes #102 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
* Operating system: windows
* Text-editors used: Vs Code
 
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
hey @dilroseR plz add the ss of the changes u have done

**Comment by dilroseR** [comment]
> hey @dilroseR plz add the ss of the changes u have done

okay

**Comment by dilroseR** [comment]
> hey @dilroseR plz add the ss of the changes u have done



> > hey @dilroseR plz add the ss of the changes u have done
> 
> okay


https://user-images.githubusercontent.com/70878223/126616122-cb2c2be0-ca71-4b49-a24b-9506303b940a.mp4

**Comment by Ayan-thecodeking** [comment]
@dilroseR what u have added new ,,,,?

**Comment by dilroseR** [comment]
> @dilroseR what u have added new ,,,,?

Can't you see the transition. before anchor tags wasn't popping but it is

**Pull request closed without merging**
