### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aditya664**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
hey @Aditya664 what you have updated ...let me know ..also attach the ss

**Comment by Aditya664** [comment]
Check out link bellow

**Comment by Aditya664** [comment]
Screenshot_2021-09-09-14-42-41-453_com android chrome
I am out now so I have removed the sss on the mobile

**Comment by Aditya664** [comment]
Added licence badges instead of text

**Comment by Ayan-thecodeking** [comment]
ok cool @Aditya664 ...but next time make sure to create an issue before making a PR

**Comment by Aditya664** [comment]
@Ayan-thecodeking  ok thanks man

**Pull request merged**
