### PR TITLE
Added a nice logo, adjusted some spacings and fonts, corrected spelli…

### PR DESCRIPTION
**Pull request by IAmTamal**
#75
 
# Description

--> Added round corners to the "view more" and "learn more" buttons
--> Adjusted spacings in the nav-links
--> Adjusted text color in the button on hover
--> Added an icon to the site.

Before : 

After :

Before : 

After : 

Before  : 

After :

### CODE REVIEW

**Review by Ayan-thecodeking — CHANGES_REQUESTED** [review]
hey @IAmTamal first of all solve the merge conflicts and mention the issue that u have fixed  (       #<issue.no> )

**Comment by IAmTamal** [comment]
> hey @IAmTamal first of all solve the merge conflicts and mention the issue that u have fixed ( #<issue.no> ) and add the SS too

i have tried doing what you mentioned (I am really new to all these, sorry for the extra hassle)

**Comment by Ayan-thecodeking** [comment]
> > hey @IAmTamal first of all solve the merge conflicts and mention the issue that u have fixed ( #<issue.no> ) and add the SS too
> 
> i have tried doing what you mentioned (I am really new to all these, sorry for the extra hassle)

Its ok np @IAmTamal .... u have to add the logo of coders evoke not that u have added .... dm me ill share u the logo

**Comment by IAmTamal** [comment]
> > > hey @IAmTamal first of all solve the merge conflicts and mention the issue that u have fixed ( #<issue.no> ) and add the SS too
> > 
> > 
> > i have tried doing what you mentioned (I am really new to all these, sorry for the extra hassle)
> 
> Its ok np @IAmTamal .... u have to add the logo of coders evoke not that u have added .... dm me ill share u the logo



> > > hey @IAmTamal first of all solve the merge conflicts and mention the issue that u have fixed ( #<issue.no> ) and add the SS too
> > 
> > 
> > i have tried doing what you mentioned (I am really new to all these, sorry for the extra hassle)
> 
> Its ok np @IAmTamal .... u have to add the logo of coders evoke not that u have added .... dm me ill share u the logo

Where to dm you ?  😅
Twitter, linkedin's dm doesnot works.

**Comment by Ayan-thecodeking** [comment]
> > > > hey @IAmTamal first of all solve the merge conflicts and mention the issue that u have fixed ( #<issue.no> ) and add the SS too
> > > 
> > > 
> > > i have tried doing what you mentioned (I am really new to all these, sorry for the extra hassle)
> > 
> > 
> > Its ok np @IAmTamal .... u have to add the logo of coders evoke not that u have added .... dm me ill share u the logo
> 
> > > > hey @IAmTamal first of all solve the merge conflicts and mention the issue that u have fixed ( #<issue.no> ) and add the SS too
> > > 
> > > 
> > > i have tried doing what you mentioned (I am really new to all these, sorry for the extra hassle)
> > 
> > 
> > Its ok np @IAmTamal .... u have to add the logo of coders evoke not that u have added .... dm me ill share u the logo
> 
> Where to dm you ? 😅
> Twitter, linkedin's dm doesnot works.

hey @IAmTamal are u in our discord server ??? https://discord.gg/XMuEPgCj6y join frm here and dm me

**Pull request closed without merging**
