### PR TITLE
Add 404 Page

### PR DESCRIPTION
**Pull request by ri-tae-ka**
# Description

Added a simple 404 page and styled it using CSS and added a button to redirect to home page.

Fixes # (issue no.) 
#60

## Type of change

Added a 404 page and a button in the page to allow user to redirect to the landing home page.

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
* Text-editors used: VS Code
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

Screenshot 2021-07-16 150209

### CODE REVIEW

**Comment by neelshah2409** [comment]
@ri-tae-ka Good work!! . 
PR is approved will be merged soon.

**Comment by ri-tae-ka** [comment]
@neelshah2409 as it was under DCP do i need to fill a form after successful merging of the PR.
If so please do share the form with me.

**Comment by Ayan-thecodeking** [comment]
> @neelshah2409 as it was under DCP do i need to fill a form after successful merging of the PR.
> If so please do share the form with me.

https://coders-evoke-community.github.io/CodersEvoke_website

**Comment by Ayan-thecodeking** [comment]
> https://coders-evoke-community.github.io/CodersEvoke_website



> > @neelshah2409 as it was under DCP do i need to fill a form after successful merging of the PR.
> > If so please do share the form with me.

https://forms.gle/TsnDMnxXXcrzd8VE6

**Pull request merged**
