### PR TITLE
changes in the home page and contact page

### PR DESCRIPTION
**Pull request by ishan-pf**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (146) 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system: WIndows
* Version: 10
* Text-editors used: vscode
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by ishan-pf** [comment]
Screenshot 2021-07-28 150006
Screenshot 2021-07-28 150033
Screenshot 2021-07-28 231357
Screenshot 2021-07-28 145921
Screenshot 2021-07-28 145944

**Comment by ishan-pf** [comment]
in the mobile version , i increased the width of icon to 50% , menu drop-down btn i placed it in the end by making a it a flex container , and i centered the text inside it , and changed the view button hover effect

i centered the social media icons using justify content : center and added a bit of margin -top of 2rem;

removed in the padding as the text wasn't centered in the " benefits if join us"

on footer top i made the border radius 1 rem

on header i made the border radius on both the sides 1.5rem looks better now , centered the drop down menu text , and put the drop down icon at the flex - end

contact page : corrected the border radius of header , on forms outline none , border none , border radius 1 rem , color a bit pinkish , submit button border radius

**Comment by Ayan-thecodeking** [comment]
> in the mobile version , i increased the width of icon to 50% , menu drop-down btn i placed it in the end by making a it a flex container , and i centered the text inside it , and changed the view button hover effect
> 
> i centered the social media icons using justify content : center and added a bit of margin -top of 2rem;
> 
> removed in the padding as the text wasn't centered in the " benefits if join us"
> 
> on footer top i made the border radius 1 rem
> 
> on header i made the border radius on both the sides 1.5rem looks better now , centered the drop down menu text , and put the drop down icon at the flex - end
> 
> contact page : corrected the border radius of header , on forms outline none , border none , border radius 1 rem , color a bit pinkish , submit button border radius

thanx @ishan-pf for this useful contibutions :)

**Comment by Ayan-thecodeking** [comment]
hey @ishan-pf pls resolve the merge conflicts

**Review by Ayan-thecodeking — CHANGES_REQUESTED** [review]
resolve the conflicts

**Pull request merged**
