### PR TITLE
Added AOS Feature

### LINKED ISSUE #165: Improve display feature of pages by adding AOS library features
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## Description

All the cards in all pages are static or there is not visual effects in that. That can be much improved using [AOS](http://michalsnik.github.io/aos/) library.

### PR DESCRIPTION
**Pull request by sr-sweta**
# Description

Solved issue #165. Added AOS features to home and event page. That feature needed [AOS libraby](https://github.com/michalsnik/aos#basic) links in the respective js file. 

Fixes #165 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows 8
* Version: 
* Text-editors used: VS Code
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 

Added aos libraby in script and added to index.html and event.html.

[Home Page](https://user-images.githubusercontent.com/70569920/127745022-02b279c9-faae-4b36-871d-461a1d831d5a.mp4)

[Event Page](https://user-images.githubusercontent.com/70569920/127745103-29dc8d41-5ecb-4d6c-935b-cb60c8a12473.mp4)

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
hey @sr-sweta can u add the clip or ss

**Comment by sr-sweta** [comment]
I added in the [issue comment](https://github.com/Coders-Evoke-Community/CodersEvoke_website/issues/165)

**Comment by Ayan-thecodeking** [comment]
thnx for contribution @sr-sweta

**Comment by sr-sweta** [comment]
> thnx for contribution @sr-sweta

My pleasure to contribute.

**Pull request merged**
